name: Build Go Binary

on:
  push:
    branches:
      - main  # 只有 main 分支更新时才触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Linux binary
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/app main.go
          echo "✅ Build finished: dist/app"

      - name: Package binary and assets
        run: |
          cd dist
          mkdir -p package
          mv app package/
          cp -r ../templates ../static package/ || true
          tar -czf app-linux.tar.gz -C package .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-linux
          path: dist/app-linux.tar.gz
